### ISSUE TITLE
Blog Page: Blog Archives

### ISSUE THREAD

**Issue by lauraehiller** [spacelabdev/spacelab-react#307]
Currently, the only way to get to Blog Archives is by clicking the button on either the home page or the blog page.  I suggest removing the slider that is on the blog page.  Instead, let's implement a "hidden archive".  

Basically, the first six blog cards should be shown automatically when the user navigates to the page.  When the user clicks on the "View Blog Full Archives" button, the rest of the cards are shown.

The Blog carousel component should remain the same, except the button text should be changed to read "View Full Blog" instead of "View Full Blog Archives" and should link directly to the blog page.

**Comment by megbuch** [comment]
Just for clarification, is this what you mean?

On the home page, you want to keep everything the same with the button linking to the blog page.

On the blog page, you want the blog archives to be a component that appears underneath the carousel, instead of on a separate page. Basically when a user navigates the the blog page, they see the carousel and a button which says "View Full Blog". Upon clicking that button, the archive cards appear underneath the carousel.

Is that correct? Just want to make sure before I start on it.
