### ISSUE TITLE
Bug Fix: InternalNavButton

### ISSUE THREAD

**Issue by megbuch** [spacelabdev/spacelab-react#326]
There is a bug when using the `InternalNavButton` component on the Home Page, underneath the carousel component. When using the InternalNavButton, which links to the Blog Page, it breaks the the Blog Page, **causing nothing to render and all blog archives data to be undefined**.

This issue only persists when using the InternalNavButton. When linking using `<Link />`, all works properly.

I don't know if the InternalNavButton is causing this issue, or if it might be an issue with the Blog Page or Blog Archives components.

**Comment by manuel12** [comment]
I can check this :)

**Comment by manuel12** [comment]
Hi @megbuch, is this issue still happening?  

I ask because I tested in the following way:

1. Commented  out current link to blog on blogCarousel and import and use InternalNavButton instead, here a code snippet of what I did:
```
<div className="archives-button-container">
  {/* InternalNavButton causes a bug rendering the blog page */}
  <InternalNavButton
    path="/blog"
    buttonText="View Full Blog - (Internal Nav Button)"
  ></InternalNavButton>
  {/* <button>
    <Link to={"/blog"} style={{ textDecoration: "none" }}>
      View Full Blog
    </Link>
  </button> */}
</div>
```
2. Confirm what is displayed on the site is the InternalNavButton (confirmed by the added button text):

![image](https://github.com/spacelabdev/spacelab-react/assets/4129325/a9355a2c-e44b-48b6-b63f-014385d9da83)

3. Click on the button and see results: I get Blog  view with the blog posts shown:

![image](https://github.com/spacelabdev/spacelab-react/assets/4129325/122c91a4-72a7-4272-ad71-55802fab86a2)

**Comment by megbuch** [comment]
Oh, interesting. Maybe I had made a mistake when I implemented it. If you were able to click that button and see the blog page with the posts, then it definitely works as intended. 

Thank you for testing it. 🙂

**Comment by manuel12** [comment]
> Oh, interesting. Maybe I had made a mistake when I implemented it. If you were able to click that button and see the blog page with the posts, then it definitely works as intended.
> 
> Thank you very much for testing it. 🙂
> 
> I suggest implementing the InternalNavButton here, and submitting a PR for this issue, so we can close it.

Will do so :)
