### ISSUE TITLE
Merge main branch into RELEASE branch

### ISSUE THREAD

**Issue by fjstria** [spacelabdev/spacelab-react#463]
The main branch has updates that haven't been pulled to the RELEASE branch. All changes should be pushed to RELEASE before new pull requests are accepted to main.

From now on, all new feature branches should be made off main to avoid building on top of legacy versions.

**Comment by ryanfchase** [comment]
We need to do the following:

- We should make a list of features to smoke test on the main branch, so that multiple devs can confirm the branch is ready to release
- Clear the following tickets if the work is completed
  - https://github.com/spacelabdev/spacelab-react/issues/457
  -  https://github.com/spacelabdev/spacelab-react/issues/390
  - compile full list

**Comment by fjstria** [comment]
## Bugs to address
General:
- [ ] Runtime error: NetworkError
![Image](https://github.com/user-attachments/assets/6e5545d9-3def-45b6-92e0-fa50c186375b)

Home:
- [ ] Link to blog page is still down, should we remove it for this deployment?

About:
- [ ] Scrollbar disappears when clicking on meet the team icons, causes the page to shift horizonally as you click in and out of team member profiles

Discovery:
- [ ] Need padding underneath the filters component

Podcast:
- [ ] Newsletter sign up isn't centered, also needs padding underneath

Blog:
- [ ] Same comments under Home, remove from navbar?

Donate:
- [ ] When using Debit/Credit, the input fields cover the navbar when scrolling down
- [ ] Also the input fields are restricted to a small column, let's use more horizontal space on desktop?
